repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files

    - repo: https://github.com/PyCQA/isort
      rev: 5.13.0
      hooks:
          - id: isort
            args: ["--profile", "black", "--filter-files"]

    - repo: https://github.com/psf/black
      rev: 23.12.0
      hooks:
          - id: black
            language_version: python3.12
            exclude: migrations

    - repo: https://github.com/pycqa/flake8
      rev: 7.0.0
      hooks:
          - id: flake8
