# Constants for receipt processing

from enum import Enum
from typing import Dict

from src.core.pantry.constants import Category


class ReceiptStatus(str, Enum):
    """Status of a receipt in the processing pipeline."""

    PROCESSED = "processed"
    PENDING = "pending"


SUBCATEGORIES = [
    "Baby & Toddler Food",
    "Baking Needs",
    "Beef & Lamb",
    "Beer",
    "Beverages",
    "Biscuits",
    "Breads",
    "Breakfast",
    "Butter, Margarine & Spreads",
    "Canned Food",
    "Champagne & Sparkling Wine",
    "Cheese",
    "Chicken",
    "Chilled Beverages",
    "Chilled Food",
    "Chocolates",
    "Coffee",
    "Condiments",
    "Cooking Paste & Sauces",
    "Cream",
    "Delicatessen",
    "Dried Fruits & Nuts",
    "Drink Mixers",
    "Eggs",
    "Fish & Seafood",
    "Fresh Milk",
    "Frozen Desserts",
    "Frozen Food",
    "Frozen Meat",
    "Frozen Seafood",
    "Fruits",
    "Ice Cream",
    "Infant Formula",
    "Jams, Spreads & Honey",
    "Juices",
    "Meatballs",
    "Milk Powder",
    "Non Alcoholic",
    "Noodles",
    "Oil",
    "Pasta",
    "Pork",
    "Ready-To-Eat",
    "Rice",
    "Seasonings",
    "Snacks",
    "Soups",
    "Spirits",
    "Sugar & Sweeteners",
    "Sweets",
    "Tea",
    "Uht Milk",
    "Vegetables",
    "Water",
    "Wine",
    "Yoghurt",
]

SUBCAT_TO_CATEGORY: Dict[str, Category] = {
    "Fruits": Category.FRUITS,
    "Vegetables": Category.VEGETABLES,
    "Fresh Milk": Category.DAIRY,
    "Cheese": Category.DAIRY,
    "Yoghurt": Category.DAIRY,
    "Chicken": Category.MEAT,
    "Beef & Lamb": Category.MEAT,
    "Pork": Category.MEAT,
    "Fish & Seafood": Category.SEAFOOD,
    "Frozen Seafood": Category.SEAFOOD,
    "Rice": Category.GRAINS,
    "Pasta": Category.GRAINS,
    "Noodles": Category.GRAINS,
    "Oil": Category.STAPLES,
    "Seasonings": Category.STAPLES,
    "Cooking Paste & Sauces": Category.STAPLES,
    "Baking Needs": Category.STAPLES,
    "Frozen Food": Category.FROZEN,
    "Frozen Meat": Category.FROZEN,
    "Frozen Desserts": Category.FROZEN,
    "Ice Cream": Category.FROZEN,
    "Beverages": Category.BEVERAGES,
    "Juices": Category.BEVERAGES,
    "Coffee": Category.BEVERAGES,
    "Tea": Category.BEVERAGES,
    "Water": Category.BEVERAGES,
    "Beer": Category.BEVERAGES,
    "Wine": Category.BEVERAGES,
    "Spirits": Category.BEVERAGES,
    "Snacks": Category.SNACKS,
    "Biscuits": Category.SNACKS,
    "Sweets": Category.SNACKS,
    "Chocolates": Category.SNACKS,
}
