from typing import List, Literal

from pydantic import BaseModel, Field


class RecipePromptIn(BaseModel):
    message: str = Field(..., example="What can I cook with eggs and spinach?")


class Message(BaseModel):
    role: Literal["user", "assistant", "system"] = Field(
        ...,
        example="user",
        description="Role in the conversation (user, assistant, or system)",
    )
    content: str = Field(
        ...,
        example="I have some rice and eggs. What can I cook?",
        description="Message content",
    )


class ChatPromptIn(BaseModel):
    messages: List[Message] = Field(
        ..., description="List of messages to simulate the conversation"
    )


class ChatReplyOut(BaseModel):
    reply: str = Field(
        ...,
        example="How about making egg fried rice with some soy sauce and vegetables?",
        description="Response generated by the chatbot",
    )
