"""update Auth Token field to 'token_issued_at'

Revision ID: 2091558d7781
Revises: 4eee64d974be
Create Date: 2025-06-03 17:51:05.672297

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2091558d7781"
down_revision: Union[str, None] = "4eee64d974be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth_tokens", sa.Column("token_issued_at", sa.DateTime(), nullable=True)
    )
    op.drop_column("auth_tokens", "issued_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("auth_tokens", sa.Column("issued_at", sa.DATETIME(), nullable=True))
    op.drop_column("auth_tokens", "token_issued_at")
    # ### end Alembic commands ###
