"""add pantry item table

Revision ID: 289e29499a17
Revises: 8da8a2d7b2ce
Create Date: 2025-06-12 21:21:22.998736

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "289e29499a17"
down_revision: Union[str, None] = "8da8a2d7b2ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pantry_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("item_name", sa.String(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column(
            "unit",
            sa.Enum(
                "GRAMS",
                "KILOGRAMS",
                "MILLILITERS",
                "LITERS",
                "PIECES",
                "LOAF",
                "PACK",
                name="unit",
            ),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.Enum(
                "FRUITS",
                "VEGETABLES",
                "DAIRY",
                "MEAT",
                "SEAFOOD",
                "GRAINS",
                "STAPLES",
                "FROZEN",
                "BEVERAGES",
                "SNACKS",
                "OTHER",
                name="category",
            ),
            nullable=False,
        ),
        sa.Column("purchase_date", sa.DateTime(), nullable=True),
        sa.Column("expiry_date", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pantry_item_user_id"), "pantry_item", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pantry_item_user_id"), table_name="pantry_item")
    op.drop_table("pantry_item")
    # ### end Alembic commands ###
