"""Add deleted add to chat tables

Revision ID: 2c610a8112c4
Revises: 5523fca38ca0
Create Date: 2025-07-15 15:04:52.525035

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c610a8112c4"
down_revision: Union[str, None] = "5523fca38ca0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth_tokens",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "chat_history",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "chat_session",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "configuration",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "pantry_item",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "user_accounts",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_accounts", "deleted_at")
    op.drop_column("pantry_item", "deleted_at")
    op.drop_column("configuration", "deleted_at")
    op.drop_column("chat_session", "deleted_at")
    op.drop_column("chat_history", "deleted_at")
    op.drop_column("auth_tokens", "deleted_at")
    # ### end Alembic commands ###
