"""add admin-managed models

Revision ID: 4eee64d974be
Revises: 25fb91787ebe
Create Date: 2025-06-03 17:38:29.824506

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "4eee64d974be"
down_revision: Union[str, None] = "25fb91787ebe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
