"""Add is_admin column to user_accounts table

Revision ID: 533f839e4916
Revises: 2c610a8112c4
Create Date: 2025-07-18 22:49:35.631513

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "533f839e4916"
down_revision: Union[str, None] = "2c610a8112c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_accounts", sa.Column("is_admin", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_accounts", "is_admin")
    # ### end Alembic commands ###
