"""rename 'key' to 'token' in 'AuthToken' table

Revision ID: 8da8a2d7b2ce
Revises: 2091558d7781
Create Date: 2025-06-03 22:24:24.026541

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8da8a2d7b2ce"
down_revision: Union[str, None] = "2091558d7781"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("auth_tokens", sa.Column("token", sa.String(), nullable=True))
    op.drop_index(op.f("ix_auth_tokens_key"), table_name="auth_tokens")
    op.create_index(op.f("ix_auth_tokens_token"), "auth_tokens", ["token"], unique=True)
    op.drop_column("auth_tokens", "key")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("auth_tokens", sa.Column("key", sa.VARCHAR(), nullable=True))
    op.drop_index(op.f("ix_auth_tokens_token"), table_name="auth_tokens")
    op.create_index(op.f("ix_auth_tokens_key"), "auth_tokens", ["key"], unique=1)
    op.drop_column("auth_tokens", "token")
    # ### end Alembic commands ###
