"""Add image_hash in ReceiptResult table

Revision ID: aac6af458793
Revises: 354a05adc967
Create Date: 2025-07-28 19:05:52.977538

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aac6af458793"
down_revision: Union[str, None] = "354a05adc967"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("receipt_result", sa.Column("image_hash", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_receipt_result_image_hash"),
        "receipt_result",
        ["image_hash"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_receipt_result_image_hash"), table_name="receipt_result")
    op.drop_column("receipt_result", "image_hash")
    # ### end Alembic commands ###
